# Generated by Django 4.1.1 on 2022-10-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specialties',
            field=models.ManyToManyField(to='API.specialty'),
        ),
    ]
