# Generated by Django 4.1.1 on 2022-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='niches',
            field=models.ManyToManyField(blank=True, to='API.niche'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='API.specialty'),
        ),
    ]
