# Generated by Django 4.1.1 on 2022-10-26 19:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('CLOSED', 'CLOSED'), ('FINAL REVIEW', 'FINAL REVIEW')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('mi', models.CharField(max_length=20)),
                ('last', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.specialty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
            options={
                'unique_together': {('user', 'specialty')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(through='API.UserProject', to='API.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(through='API.UserSpecialty', to='API.specialty'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='roleuser', through='API.UserRole', to='API.user'),
        ),
        migrations.CreateModel(
            name='ProjectSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.specialty')),
            ],
            options={
                'unique_together': {('project', 'specialty')},
            },
        ),
        migrations.CreateModel(
            name='ProjectNiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.niche')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project')),
            ],
            options={
                'unique_together': {('project', 'niche')},
            },
        ),
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('text_notes', models.CharField(max_length=5000)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('entry_time', models.TimeField(auto_now_add=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('last_modified_time', models.TimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.specialty')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(related_name='clients', through='API.UserProject', to='API.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='denial',
            field=models.ManyToManyField(related_name='denials', through='API.DenialProject', to='API.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='niches',
            field=models.ManyToManyField(through='API.ProjectNiche', to='API.niche'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_entries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.projectentry'),
        ),
        migrations.AddField(
            model_name='project',
            name='specialties',
            field=models.ManyToManyField(through='API.ProjectSpecialty', to='API.specialty'),
        ),
        migrations.AddField(
            model_name='denialproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.project'),
        ),
        migrations.AddField(
            model_name='denialproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user'),
        ),
        migrations.AlterUniqueTogether(
            name='denialproject',
            unique_together={('user', 'project')},
        ),
    ]
