# Generated by Django 4.1.1 on 2022-10-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectentry',
            name='specialty',
        ),
        migrations.AddField(
            model_name='projectentry',
            name='niche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.niche'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='denials',
            field=models.ManyToManyField(blank=True, related_name='denial_users', to='API.user'),
        ),
    ]
