# Generated by Django 4.1.1 on 2022-10-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='specialties',
        ),
    ]
