# Generated by Django 4.1.1 on 2022-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='niches',
            field=models.ManyToManyField(to='API.niche'),
        ),
    ]
