# Generated by Django 4.1.1 on 2022-12-01 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_project_denied_users_alter_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nichetoproject',
            name='niche',
        ),
        migrations.RemoveField(
            model_name='nichetoproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='specialtytoproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='specialtytoproject',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='usertoproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usertoproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='DenialToProject',
        ),
        migrations.DeleteModel(
            name='NicheToProject',
        ),
        migrations.DeleteModel(
            name='SpecialtyToProject',
        ),
        migrations.DeleteModel(
            name='UserToProject',
        ),
    ]
