# Generated by Django 4.1.1 on 2022-12-06 03:53

import API.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0006_alter_niche_description_alter_niche_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mi', models.CharField(max_length=40, unique=True, validators=[API.models.contains_illegal_chars, API.models.validate_name])),
                ('balance', models.IntegerField(validators=[django.core.validators.MaxValueValidator(-2000000000), django.core.validators.MinValueValidator(-2000000000)])),
                ('niches', models.ManyToManyField(to='API.niche')),
                ('specialties', models.ManyToManyField(to='API.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
